apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: wordpress
data:
  init.sql: |
    CREATE USER 'crunchops'@'%' IDENTIFIED BY 'crunchops@123';
    GRANT ALL PRIVILEGES ON wordpress_db.* TO 'crunchops'@'%';
    FLUSH PRIVILEGES;
